json.first @user.first_name
json.last @user.last_name
json.address @user.address
json.city @user.city
json.state @user.state
json.zip @user.zip
json.id @user.id
json.email @user.email
json.phone @user.phone
json.dob @user.dob
json.auth_token @user.auth_token
json.avatar_url @user.avatar.url
